name: GCP plot daily snapshot
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'   # catches CEST
    - cron: '0 17 * * *'   # catches CET

jobs:
  grab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Skip if today’s file already exists
        run: |
          file="plots/gcp24h_$(date -u +%Y-%m-%d)_18-00.png"
          if [ -f "$file" ]; then
            echo "Snapshot already taken." && exit 0
          fi
          mkdir -p "$(dirname "$file")"
          curl -sS -o "$file" https://global-mind.org/gcpdot/plot.png
      - name: Commit & push
        run: |
          git config user.name  "gcp-bot"
          git config user.email "bot@example.com"
      
          # Stage new PNG(s)
          git add plots/*.png
      
          # Commit only when something changed
          if git diff --cached --quiet; then
            echo "Nothing new to commit."
            exit 0
          fi
      
          git commit -m "auto snapshot $(date -u)"
          git push origin $(git rev-parse --abbrev-ref HEAD)
