name: GCP plot daily snapshot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'        # 18:00 CEST
    - cron: '0 17 * * *'        # 18:00 CET

jobs:
  grab:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ---------- skip if file already exists ----------
      - name: Skip if today’s file already exists
        run: |
          file="plots/gcp24h_$(date -u +%Y-%m-%d)_18-00.png"
          if [ -f "$file" ]; then
            echo "Snapshot already taken." && exit 0
          fi

      # ---------- headless screenshot of 2‑nd canvas ----------
      - name: Capture 24‑hour graph (2‑nd canvas)
        run: |
          npm install -D playwright-chromium
          npx playwright install chromium

          mkdir -p plots
          file="plots/gcp24h_$(date -u +%Y-%m-%d)_18-00.png"
          npx playwright screenshot \
            https://www.global-mind.org/gcpdot/ \
            "$file" \
            --selector=canvas:nth-of-type(2)

      # ---------- commit & push ----------
      - name: Commit & push
        run: |
          git config user.name  "gcp-bot"
          git config user.email "bot@example.com"

          git add plots/*.png
          if git diff --cached --quiet; then
            echo "Nothing new to commit." && exit 0
          fi

          git commit -m "auto snapshot $(date -u)"
          git push origin $(git rev-parse --abbrev-ref HEAD)
