name: GCP plot daily snapshot
on:
  schedule:
    - cron:  '0 20 * * *'   # 20:00 UTC every day
jobs:
  grab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Fetch 24 h plot
        run: |
          mkdir -p plots
          file="plots/gcp24h_$(date -u +%Y-%m-%d_%H-%M).png"
          curl -s -o "$file" https://global-mind.org/gcpdot/plot.png
      - name: Commit & push
        run: |
          git config user.name  "gcp-bot"
          git config user.email "bot@example.com"
          git add plots/*.png
          git commit -m "auto snapshot $(date -u)" || echo "Nothing to commit"
          git push
