name: GCP plot daily snapshot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'        # 18:00 CEST
    - cron: '0 17 * * *'        # 18:00 CET

jobs:
  grab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Skip if today’s file already exists
      - name: Skip if file exists
        run: |
          file="plots/gcp24h_$(date -u +%Y-%m-%d)_18-00.png"
          if [ -f "$file" ]; then
            echo "Snapshot already taken." && exit 0
          fi

      # Install Playwright once and capture the canvas
      - name: Capture 24‑hour graph (2‑nd canvas)
        env:
          FILE: plots/gcp24h_$(date -u +%Y-%m-%d)_18-00.png
        run: |
          npm install -D playwright-chromium
          npx playwright install chromium

          mkdir -p plots

          node - <<'NODE'
          const { chromium } = require('playwright-chromium');
          (async () => {
            const file = process.env.FILE;
            const browser = await chromium.launch();
            const page = await browser.newPage({viewport:{width:550,height:240}});
            await page.goto('https://www.global-mind.org/gcpdot/gcpchart.php', {waitUntil:'networkidle'});
            await page.waitForTimeout(2000);               // give JS time to draw
            const canvas = await page.$('canvas');
            await canvas.screenshot({path: file});
            await browser.close();
          })();
          NODE

      # Commit & push if a new PNG landed
      - name: Commit & push
        run: |
          git config user.name  "gcp-bot"
          git config user.email "bot@example.com"
          git add plots/*.png
          if git diff --cached --quiet; then
            echo "Nothing new to commit." && exit 0
          fi
          git commit -m "auto snapshot $(date -u)"
          git push origin $(git rev-parse --abbrev-ref HEAD)
